# This file is generated by cargo2rulesmk.py --run --config cargo2rulesmk.json.
# Do not modify this file as changes will be overridden on upgrade.

LOCAL_DIR := $(GET_LOCAL_DIR)
MODULE := $(LOCAL_DIR)
MODULE_CRATE_NAME := proc_macro_error
MODULE_SRCS := \
	$(LOCAL_DIR)/src/lib.rs \

MODULE_RUST_EDITION := 2018
MODULE_RUSTFLAGS += \
	--cfg 'feature="default"' \
	--cfg 'feature="syn"' \
	--cfg 'feature="syn-error"' \
	--cfg 'skip_ui_tests' \

MODULE_LIBRARY_DEPS := \
	external/rust/crates/proc-macro-error-attr \
	external/rust/crates/proc-macro2 \
	external/rust/crates/quote \
	external/rust/crates/syn \

include make/library.mk
